# Port
server.port: 8080

#
# MySQL DataSource settings
#
spring:
  # DataSource settings: Login
  datasource:
    url: jdbc:mysql://localhost:3306/yourdbName?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password:
    
  jpa:
    # Show or not log for each sql query
    show-sql: true
    database: MYSQL
    open-in-view: false
    # The SQL dialect makes Hibernate generate better SQL for the chosen database
    hibernate:
      # Hibernate ddl auto (create, create-drop, update, none)
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
                    
  # Set time zone for Json Serializer to Europe/Paris
  jackson:
    time-zone: Europe/Paris  
    
  # LIQUIBASE
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml
    default-schema: yourdbName
    # chang to false
    drop-first: false
    # change to true 
    enabled: true 
    url: jdbc:mysql://localhost:3306/yourdbName?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    user: root
    password:
      
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: '{client_ID}'
            clientSecret: '{clientSecret}'
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope: profile, email
            
          facebook:
            clientId: '{client_ID}'
            clientSecret: '{clientSecret}'
            redirectUri: '{baseUrl}/oauth2/callback/{registrationId}'
            scope: email, public_profile
        provider:
          facebook:
            authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)
          custom-google:
            issuer-uri: https://accounts.google.com
            
app:
  auth:
    tokenSecret: '{tokenSecret}'
    tokenExpirationMsec: 864000000
  oauth2:
    authorizedRedirectUris:
    - http://localhost:3000/oauth2/redirect
    - myandroidapp://oauth2/redirect
    - myiosapp://oauth2/redirect